### ISSUE TITLE
Autocomplete widget escapes provided values

### ISSUE THREAD

**Issue by tonthon** [Pylons/deform#103]
When using widget.AutocompleteWidget, the values provided are escaped.
For example when providing

<pre code='python'>
 [u"John & Son"]
</pre>

The resulting generated javascript is :

<pre>
$('#' + oid).autocomplete({source: ["John &amp;amp; Son"] ...
</pre>

In autocomple_input.pt :

<pre>
- $('#' + oid).autocomplete({source: ${values}});
+ $('#' + oid).autocomplete({source: ${structure:values}});
</pre>

Fix the issue.

**Comment by stevepiercy** [comment]
Closed by https://github.com/Pylons/deformdemo/pull/75
