### ISSUE TITLE
Re-Merge development dependency on setuptools_git

### ISSUE THREAD

**Issue by dwt** [Pylons/deform#146]
As you cannot build an sdist correctly without it. I believe it was this commit: 32b12063ccca86d41246dd1358bb6662c4c6824e

Without it all the package data files are not included in the sdist (and therefore nothing works).

**Comment by tisdall** [comment]
oi..  I just got stung by this.  It seems that the setuptools-git developers suggest adding it to `setup_requires` as stated here and elsewhere:  https://pypi.python.org/pypi/setuptools-git/1.1#gotchas
