### ISSUE TITLE
deform.Set DeprecationWarning is always triggered

### ISSUE THREAD

**Issue by dairiki** [Pylons/deform#175]
The `from .schema import Set` in `deform/__init__.py` triggers the deprecation warning for `deform.Set` as soon as `deform` or one of it’s submodules is imported.  I.e. this will fail with a `DeprecationWarning`:

```
python -We::DeprecationWarning -c 'import deform.schema'
```

I’m not sure what the best way to fix this is.  Maybe wrap the imports in `__init__.py` between a calls to [__show__.off and __show__.on](http://docs.zope.org/zope.deprecation/api.html#temporarily-turning-off-deprecation-warnings)?  (This would also require, I think, a duplicate call to `deprecated('Set', '...')` in `__init__.py` in order to trigger the warning when `deform.Set` is accessed.)

(If this is deemed a reasonable way to proceed, I can produce a pull request.)

**Comment by stevepiercy** [comment]
Closing as won't fix.
