### ISSUE TITLE
Default action, change to '#' valid HTML5

### ISSUE THREAD

**Issue by crooksey** [Pylons/deform#201]
At present if no action is specificed, the default is 

```
action=""
```

However, this is not valid HTML5 and also causes varied results, I had the same code on the same browser, working differently.

The simple solution is so change the default to:

```
action="#"
```

Which is valid HTML5 and also causes the page to load the same url as currently on.

Pull request to follow in next few minutes.

**Comment by Themanwithoutaplan** [comment]
The [spec](https://html.spec.whatwg.org/multipage/forms.html#attr-fs-action) says "The action and formaction content attributes, if specified, must have a value that is a valid non-empty URL potentially surrounded by spaces." "#" is not a valid URL.

The spec goes on to say that that empty string is the value for an action if none is supplied. However, some browsers will not submit a form if there is no action provided. The docs can be extended but current behaviour seems reasonable to me: client code gets to decide what the action should be.

**Comment by miohtama** [comment]
Closing this issue as Deform 2.0 has taken over. Please reopen if you still feel the behavior should be changed.
