### ISSUE TITLE
Deform doesn't work if js files are included after the generated forms

### ISSUE THREAD

**Issue by dwt** [Pylons/deform#211]
We recently encountered a bug with code like this: https://github.com/Pylons/deform/blob/master/deform/templates/timeinput.pt#L18

The problem is that if we move all our js files to the end of the body tag (as is sometimes advisable for speed reason) that code just bombs, as the deform symbol is not defined yet.

The workaround I  would propose, is to either require only jQuery to be loaded first, and then use `$(function(){...})` to protect it, or to generate code that directly hooks into document ready like this:

```
function ready(fn) {
  if (document.addEventListener) {
    document.addEventListener('DOMContentLoaded', fn);
  } else {
    document.attachEvent('onreadystatechange', function() {
      if (document.readyState === 'interactive')
        fn();
    });
  }
}
```

**Comment by miohtama** [comment]
Currently Deform templates refer to jQuery in body `<script>` tags.

This is an unfortunate design choice and won't be fixed until Deform 3.0.
