### ISSUE TITLE
Feature request: Angularjs support

### ISSUE THREAD

**Issue by AnderUstarroz** [Pylons/deform#263]
Hi, 
Would it be hard rendering the forms using the awesome library **Angularjs**  rather than jquery?

**Comment by tisdall** [comment]
I have this in my code:
```
from pkg_resources import resource_filename
from deform import Form

Form.set_zpt_renderer((
    resource_filename('myproject', 'templates/deform/'),
    resource_filename('deform', 'templates')
))
```

This allows me to over-write any of the `.pt` template files in deform with my own versions by placing them in `myproject/templates/deform/`.

If you had the same set up, you could replace jquery with Angularjs by editing each template which made use of jquery and make the same sort of effect happen with Angularjs.  You'd then have to replace some of the plugins.

When you're all done, you may have something that does what it's already doing but with Angularjs!  ..wait, what?

**Comment by AnderUstarroz** [comment]
That's great, that will be my way to go. Thanks a lot!
Just wondering about the Bootstrap compatibility... I've seen the branch **deform2** which was supposed to include bootstrap but it seems to be not longer maintained. Do you know why?

**Comment by dairiki** [comment]
@AnderUstarroz The 2.0 branch of ``deform`` (officially still in alpha — latest release 2.0a2) uses bootstrap 3.x.

**Comment by AnderUstarroz** [comment]
Yes, and the last commit was submitted 2 years ago... It lacks of all bug fixes submitted during that period.

**Comment by tisdall** [comment]
@AnderUstarroz - The master branch has the latest deform 2.0 branch.  That `deform2` branch is dead.  I see now that there's a 'feature.angular' branch that seems to be forgotten.

**Comment by goodwillcoding** [comment]
deform is fairly extensible, you can emplment angular support on top of it if you wish. However that is not the stated goal of the project.
