### ISSUE TITLE
static files not included when installing from git with pip

### ISSUE THREAD

**Issue by binbrain** [Pylons/deform#271]
Using pip to install deform directly from github in Python 3.4.2. None of the static files (js, css, po, mo, pt, etc...) are included.

```
pip install git+git://github.com/Pylons/deform
```

This is easily fixed by adding a MANIFEST.in file with the following.
```
recursive-include deform *.pt *.po *.mo *.rst *.eot *.svg *.ttf *.woff *.css *.js *.md *.png *.gif
```

**Comment by mcdonc** [comment]
We use setuptools-git to do this for us; we (really, I) prefer not to maintain a manual MANIFEST.in file.  See the epic issue thread in the Pyramid issue tracker about this at https://github.com/Pylons/pyramid/issues/121 .  Apologies, none of the arguments there have swayed us towards adding one to any Pylons project, and we haven't found a really nice way of automating the creation of a MANIFEST.in.

**Comment by tisdall** [comment]
#257 as a solution?
