### ISSUE TITLE
deform repeats id on same page if i render two form.

### ISSUE THREAD

**Issue by ShrinivasMese** [Pylons/deform#272]
if there is two forms on same page then it gives same id to defferent nodes.
deform.addcallback() will not process on two different id's. it will process only on first element.

then what about second element? we manually add that script.

**Comment by tisdall** [comment]
Have you tried setting the `formid` on the `Form` object?  It defaults to `'deform'` but you'd need to set it to different values if you have more than one form on the page.

**Comment by tseaver** [comment]
Per the [`deform.Form` docs](http://deform.readthedocs.org/en/latest/api.html#deform.Form):

> `formid`:    The identifier for this form. This value will be used as the HTML `id` attribute of the rendered HTML form. It will also be used as the value of a hidden form input control (`__formid__`) which will be placed in this form’s rendering. You should pass a string value for formid when more than one Deform form is placed into a single page and both share the same action. When one of the forms on the page is posted, your code will to be able to decide which of those forms was posted based on the differing values of `__formid__`. By default, `formid` is "deform".

**Comment by ShrinivasMese** [comment]
i request you to reopen this issue. 
yes i know __formid__ i used it. i think you are not getting my question or explanation. 

in my case i want to create, update, delete some entity(i.e. user).
so on same page i created form with __formid__ for CREATE operation. 
and for UPDATE operation i given different __formid__ for that form. here i am using same schema for both forms.

i used Date widget. adding datepicker to input type date element. deform is adding script for datepicker.

<script type="text/javascript">
   deform.addCallback(
     'deformField3',
     function(oid) {
       if (!Modernizr.inputtypes['date'] ||
           "date" != "date"){
         $('#' + oid).pickadate({"selectMonths": true, "submitFormat": "yyyy-mm-dd", "selectYears": true, "format": "yyyy-mm-dd"});
       }
     }
   );
  </script>

and same script will repeated on UPDATE opeartion. 

now deformField3 id is repeated two times. script is also attached two times. but the main problem is script will not executed for 2nd same id. 

so deform should check whether the given id is already present on page or not.

**Comment by tisdall** [comment]
> so deform should check whether the given id is already present on page or not.

This is kind of out of scope for deform to do.  It's possible that you generate your HTML page from different components that may have no concept of each other.  So, it's important to make sure there's no duplication of id's at a higher level than deform can really by responsible for.  It's also part of the HTML standard that no two DOM elements should have the same id (this includes forms, but also everything else).

Any way, it seems like you might be hinting at some sort of actual issue with deform, but it's hard to piece together from what you're saying.  It'd be far easier if you can create a minimal repeatable example demonstrating the issue you're having.

**Comment by ShrinivasMese** [comment]
<blockquote><p>It's also part of the HTML standard that no two DOM elements should have the same id (this includes forms, but also everything else).</p></blockquote>

<blockquote><p>deform is a Python HTML form generation library. </p></blockquote>

when we are generating two forms on same page by using deform HTML form generation library.
then deform gives same id to different  DOM elements.
<blockquote><b>so deform is not following  HTML standard.</b></blockquote>

so i already told that deform needs to follow HTML standard.

**Comment by tisdall** [comment]
After looking at this some more, I think the issue is that you're not providing a counter to your different forms.  Take a look at http://deform2demo.repoze.org/multiple_forms/  

from the [docs](http://docs.pylonsproject.org/projects/deform/en/latest/api.html#deform.Field):
> counter, if passed, should be an itertools.counter object (useful when rendering multiple forms on the same page, see http://deformdemo.repoze.org/multiple_forms/.

If all forms are working from the same counter object then you'll get unique id values across the page.

**Comment by ShrinivasMese** [comment]
yes i am using counter object and passing it to form. 
but one form is on main page and second form is on a ajax loaded modal.
in this particular case id's of the nodes are the same. so how can i prevent it from duplication of same id's?

**Comment by tisdall** [comment]
Well, if you retain that counter object between the two calls that you can ensure unique numbering, but that's probably not practical.  The other alternative is to include the next count number with the ajax request to inform what the next number that isn't taken is.  Or, an easy but brittle method would be to initialize the counter on the ajax responder to something sufficiently high to avoid repeating (like 1000).

**Comment by ShrinivasMese** [comment]
Yes finally we got answer. Thank you so much.
