### ISSUE TITLE
Losing tabbed form for internationalization

### ISSUE THREAD

**Issue by J20S** [Pylons/deform#288]
Hi guys,
I am following the deform doc to internationalize my webapp. 
http://deform.readthedocs.org/en/latest/i18n.html
However, after changing from the default renderer to the customised ZPT renderer where you can see in the above link, I lose my tabbed forms which are supposed to be supported by deform_bootstrap. All of the contents are now displayed in a vertical manner instead of in a tabbed form. Any hints on how to get it fixed?

Any help will be greatly appreciated!

Cheers,
James

**Comment by miohtama** [comment]
Closing this issue as deform_bootstrap no longer exist.
