### ISSUE TITLE
RichTextWidget documentation unclear, scattered

### ISSUE THREAD

**Issue by Jeremydavisvt** [Pylons/deform#291]
To specify TinyMCE options in [RichTextWidget](http://docs.pylonsproject.org/projects/deform/en/latest/api.html#deform.widget.RichTextWidget), docs say

> ##### options = None
> 
> Options to pass to TinyMCE that will override default_options.

Options must be 1 tuple with 2 tuples nested, the key and the value. For example, to enable spellcheck, you would write:

```
RichTextWidget(options=(('browser_spellcheck', True),))
```

In the TinyMCE world, this would [translate](http://www.tinymce.com/wiki.php/Configuration:browser_spellcheck) to:

```
browser_spellcheck : true 
```

This is sort of explained in the non-bolded "options" section of RichTextWidget, but is vague and doesn't provide examples. Suggest merging the two "options" sections with above example and language.

**Comment by miohtama** [comment]
Fixed in http://deformdemo.repoze.org/richtext/
