### ISSUE TITLE
Select 2 Template code

### ISSUE THREAD

**Issue by Mr-F** [Pylons/deform#292]
Hi all,

I think I have an issue, and before I go ahead and create a patch and submit a pull request I wondered if I could check this with someone, incase it's just something odd with my setup or me being dumb.

So I have a select2 widget which allows the user to select multiple entries.  The data that is use to populate the select are tuples of the form "(db_ID, display_name)".  The problem is that when this is generated and compare again the previously selected values we sometimes get other values appearing.  I've traced this down to the following line of code in select2.pt

```
(multiple and item[0] in cstruct or item[0] == cstruct)
```

So basically, when multiple is true you do a comparison like:

```
(true and "52" in "52" or "52" == "52")
```

you the value is preselected correctly.  However, if you do this again but with a cstruct value of 152:

```
(true and "52" in "152" or "52" == "152")
```

The value is again preselected, but it shouldn't be.  I believe the simple solution to this would be to simply convert the cstruct to a list, even if it is a list of one item and then say in.  Also by doing this you don't need to have the additional "and" or "or" and simply use an "in" test.  So at the top of the template have something like this:

```
<?python
    cstruct = cstruct.split(',')
?>
```

Then replace the lines which deal with marking an option as selected to:

```
item[0] in cstruct
```

What do you think?  Am I missing something obvious or is this fine and I should go ahead and make the modification and submit a pull request?

Thanks

Keith

**Comment by miohtama** [comment]
I reworked select (select2) code. Can you please confirm if this is an issue anymore and reopen the issue if this is the case.
