### ISSUE TITLE
Deform 2 Docs confusing

### ISSUE THREAD

**Issue by mjmare** [Pylons/deform#303]
For a newbie it is not very clear what the status and use of Deform 2 is.

The Deform pypi page mentions that the most recent version of Deform is 2.0a. However pip installing deform will install 0.9.9. So one has to pin 2.0.a2.
Deform2 is in alfa since 2013?
Docs are not updated to reflect the current version?
The deform demo uses deform 1?
There is a http://deform2demo.repoze.org (which looks good!), but all its links point to the deform 1 demo/docs. The 'show in context' links are broken.
Deform 2 requires Bootstrap 3 and JQuery 2 to be installed manually. This is only mentioned in the migration notes. Not a place where a new user would look.

**Comment by miohtama** [comment]
Thank you for the feedback.

As of today http://deformdemo.repoze.org/ has been updated.

Furthermore http://docs.pylonsproject.org/projects/deform/en/latest/ points to 2.0

**Comment by mjmare** [comment]
Nice to see that Deform is resurrected! Thanks for your efforts. Docs look good.
