### ISSUE TITLE
Select2 widget library out of date

### ISSUE THREAD

**Issue by chrxr** [Pylons/deform#310]
Hi there,

please could the select2 widget resources and template be brought up-to-date. The version currently included is 3.4, whereas the current version is 4.0.3.

V4.0+ includes the ability to use ajax directly with the select element without resorting to hidden input fields.

Thanks

**Comment by miohtama** [comment]
Hi @chrxr 

We definitely need to do this? Can you open a pull request on this? PR will run automatic test suite and it will bark if there are any incompatible changes.

**Comment by mikmatko** [comment]
Attempted this. See pull request #322

**Comment by miohtama** [comment]
Merged, closing the issue.
