### ISSUE TITLE
is requirement Firefox 43 or 45

### ISSUE THREAD

**Issue by tisdall** [Pylons/deform#321]
In https://github.com/Pylons/deform/blob/master/CONTRIBUTING.md it says Firefox 43 and then everything else says Firefox 45.  I'm thinking the "43" should be changed to a "45" but I don't really know.

@miohtama - You put this in originally, so I'm guessing you know which is correct.

**Comment by miohtama** [comment]
Fixed. Also clarified why we need to stick for this Firefox version for a while.
