### ISSUE TITLE
Regression - Deform 2.0.1 is ignoring SelectWidget's default values.

### ISSUE THREAD

**Issue by Rich43** [Pylons/deform#323]
I made this little example but I cannot get it to pre-select anything in the SelectWidget: http://pastebin.com/XmAGzB0j

Can someone look into the deform code and fix this?

**Comment by miohtama** [comment]
Thanks! I'll take a look.

**Comment by Rich43** [comment]
Reverting to 2.0a2 fixes it, I just installed it with pip install deform==2.0a2 and ran the pastebin demo again and it suddenly works. Definitely a regression in 2.0.1 :)
Probably want to look at the code changes between the two versions, see who committed some code that messed up the SelectWidget's default value finder.

**Comment by miohtama** [comment]
2.0.2 released with a fix.
