### ISSUE TITLE
Alert for form success

### ISSUE THREAD

**Issue by ngoonee** [Pylons/deform#324]
Currently, if validation fails and we render the ValidationFailure object, the resulting form contains an alert at the top, a clear indication that the something was wrong with the input data.

Would it be possible to have the opposite, a 'success' alert built-in to the form. The exact string being put into the alert could probably be defined as an argument to render, something like

`my_form.render(success='<strong>Insert</strong> successful')`

I'm currently doing this manually, but that requires me to have additional code both on the python side and the view (template) side for EACH form in my app. Would be nice to bake it in.

**Comment by bertjwregeer** [comment]
Generally when you submit a form and it is successful you redirect to an alternate page using a 303 when form submission is successful due to how browsers treat POST.

**Comment by ngoonee** [comment]
> Generally when you submit a form and it is successful you redirect to an
alternate page using a 303 when form submission is successful due to how
browsers treat POST.

I prefer to stay on the same page as the user is likely to want to use the
form repeatedly in some instances (and the same page also shows data which
has previously been entered). I find it a waste of time to go back and
forth between pages for data entry like tasks.

**Comment by mmerickel** [comment]
You can redirect to the same page. It switches the browser into GET mode so that when the user refreshes the page it doesn't try to re-submit the previous form data.

**Comment by tisdall** [comment]
You may want to try using the pyramid "flash" messages.  You'd store a "successful" message on the POST and then on the first GET it would display the "flash" message.

http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/sessions.html#flash-messages

**Comment by ngoonee** [comment]
I'm not having an issue with GET mode (I handle both POST and GET in the same function anyway, which calls a subfunction to generate the form as necessary). Would be nice if I could indicate success.

Right now I'm already using flash messages, but something built-in would be a bit better (using the same template as the warnings which come out when there's a submission problem).

**Comment by ngoonee** [comment]
I'm not having an issue with GET mode (I handle both POST and GET in the same function anyway, which calls a subfunction to generate the form as necessary). Would be nice if I could indicate success.

Right now I'm already using flash messages, but something built-in would be a bit better (using the same template as the warnings which come out when there's a submission problem).

**Comment by miohtama** [comment]
@ngoonee Thank you for the feedback. In the case you need this functionality often, I suggest you subclass `deform.form.Form` class and build your specific success functionality in there. If you find an elegant solution to do this we can also add this as an example to deformdemo package. 

Currently, as most web forms do some sort redirect after success, flash message is the best practice. If one needs themed flash messages please feel free to see examples in https://websauna.org/docs/narrative/misc/messages.html

If you want to pursuit this feel free to open a pull request.  I'll leave this issue open for now for two months.

**Comment by ngoonee** [comment]
Thanks, since the consensus seems to be that flash messages are more suitable (and I already use them) I'll drop this.
