### ISSUE TITLE
docs missing in PyPi releases

### ISSUE THREAD

**Issue by frispete** [Pylons/deform#333]
It would be nice to include them in the next release...

**Comment by miohtama** [comment]
It's intentional they are not in the release. Because most of the time you end up installing Deform it goes to `site-packages` and docs end up just paying extra payload in the archive and on disk.

If you want to read docs you can grab the source code from Github anyway. Or even better, read online.

However we can discuss.

**Comment by frispete** [comment]
For the majority of users, you're probably right, but you miss some points:
- deform is part of the pylons project, and one characteristic of this project is: it is sticking with its own standards, and every pylons package contains its documentation
- quite a few linux distributions out there will package from the tarball, and while this isn't the recommended way to install that stuff, we're proud to unit test most packaged projects in every build.

The latter may sound as a waste, but believe me, we're acting as a canary, if things go south. I'm sure, debian is acting that way as well. Sure, most projects are tox testing the check ins, but this is a second line of defense, and I discover more issues that way, than I would like. See [here](https://build.opensuse.org/project/monitor/home:frispete:python3).

We're also proud, that, given you take care to install the doc packages as well, you have documentation at hand, even if you're somewhere without internet...

Since documentation is laying around in compressed state for the casual user, the amount of "wasted" space is manageable, isn't it.

**Comment by mmerickel** [comment]
@miohtama It's standard practice in all of the other pylons projects ship their docs and tests in the sdist. They are excluded from wheels which you should consider uploading from deform.

In fact, you added a `MANIFEST.in` which is different from how we package most other projects and it would be good to reconsider.

- Delete `MANIFEST.in`.
- Install `setuptools-git` before running `python setup.py sdist bdist_wheel`.
- Every file in the repo will be included in the sdist. Only data within the actual package is included in the wheel.

We are on the cusp of a point where this will be even better as well thanks to PEP 518. We will be able to add a `pyproject.toml` file to each repo which automatically installs `setuptools-git` for us. We are likely within months of this happening but until then it's a manual process.

**Comment by miohtama** [comment]
@mmerickel @frispete Thank you for the good feedback. Reopened and added this as sprintable.

**Comment by tigerfoot** [comment]
Also don't forget to readd the LICENSE file ;-)
