### ISSUE TITLE
_FieldStorage SchemaType error message overrides user-provided colander.Invalid messages

### ISSUE THREAD

**Issue by ngoonee** [Pylons/deform#338]
The `_FieldStorage` class does a 'weak attempt at duck-typing' (comment from the source https://github.com/Pylons/deform/blob/master/deform/widget.py#L60) which prevents previously raised `colander.Invalid` exceptions from being rendered.

This is suboptimal as the error message itself is not clear, especially to the end-users of the web app.

http://stackoverflow.com/questions/42759940/deform-file-upload-overrides-my-error-message-with-invalid-pstruct-not-a-fields has a bit more detail code-wise, but the root issue is as above.

**Comment by stevepiercy** [comment]
This should have been resolved in #360. Closing. If not, please reopen or create a new issue.
