### ISSUE TITLE
FileUploadWidget raises error if file is not provided

### ISSUE THREAD

**Issue by kuzmich** [Pylons/deform#339]
If you create a simple file upload form like http://deformdemo.repoze.org/file/, and submit a form without any file, you'll get an error `Invalid pstruct: {'upload': "b'' is not a FieldStorage instance"}`. Probably it's Python 3 only specific problem.

Versions used:
- deform: 2.0.4
- Python: 3.6.0

The exception is raised by `_FieldStorage ` [here](https://github.com/Pylons/deform/blob/master/deform/widget.py#L66). The qucik fix is just add `b''` as an empty cstruc [here](https://github.com/Pylons/deform/blob/master/deform/widget.py#L62).

I'd like to fix it, but I'm not sure how to do it properly. As stated [here](https://docs.python.org/2/reference/lexical_analysis.html#string-literals),
> A prefix of 'b' or 'B' is ignored in Python 2; it indicates that the literal should become a bytes literal in Python 3

so we can use it.

Do I also have to create an unit test for it? Existing tests just skip the value for file upload is file is not selected - see [here](https://github.com/Pylons/deform/blob/master/deform/tests/test_widget.py#L1332) for example.

There's also a similar issue #338 .

**Comment by stevepiercy** [comment]
Fixed in #360. If not please reopen or create a new issue.
