### ISSUE TITLE
Prepare for Bootstrap 4

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/deform#355]
This is a placeholder for discussing how to upgrade deform from Bootstrap 3 to Bootstrap 4, assuming that is desired.

## Questions
1. Do we try to make deform compatible between both BS3 and BS4?
2. If such compatibility is not possible or desired, how do we handle breaking changes?

**Comment by bouillon** [comment]
I think to support Bootstrap3 is not important.
Much more important to migrate widgets to BS4. Nobody will start a new project with BS3 and for the moment deform with bs4 is not usable.

**Comment by bertjwregeer** [comment]
Hey @mcdonc I remember you twittering something about Boot Strap 4, would this be an easy migration?

**Comment by stevepiercy** [comment]
[BS4 provides a migration guide](https://getbootstrap.com/docs/4.3/migration/).

**Comment by sydoluciani** [comment]
For the sake of quick test, 
cloned deformdemo 
did pip install -e . 
copied to override two bootstrap 3 files with bootstrap 4 files:
bootstrap.min.css file to python3.7/site-packages/deform/static/css/
bootstrap.min.js to python3.7/site-packages/deform/static/scripts/

started deformdemo and checked couple of widgets and all working.

JQuery and Popper that is used in bootstrap 4 shall be included using CDN
therefore no changes in deform itself.

looking at deform/widget.py requirements, only tinymce has specific version, the rest 
have version requirements set to None, so we can start with minimum changes and replacing bootstrap.min.css and bootstrap.min.js, and add new resources if there are incompatibility.

The question is:
for new branch, would you prefer to add a new directory like static_bs4 to contain bootstrap 4 files
and change:
config.add_static_view('deform_static', 'deform:static/')
to
config.add_static_view('deform_static', 'deform:static_bs4/')
to test bootstrap4 and fallback if required, 
or just start overriding the bootstrap 3 files with bootstrap4 ?

**Comment by bertjwregeer** [comment]
Start overriding the bootstrap 3 files with bootstrap 4.

I have no desire to maintain both BS3 and BS4, we simply don't have the capacity or the team to do so.

**Comment by stevepiercy** [comment]
2.5 years after this was suggested, we've seen the EOL of Python 2.7 and 3.4. If we are going to release a new Deform with BS4—I guess we could call it Deform 3.0—then I would suggest we drop support for those Pythons and add up through 3.8.

**Comment by bertjwregeer** [comment]
I'm all for making it a new release that is not Py2.7 compatible (if only because we no longer test on it... not necessarily because we go through and explicitly make it incompatible).

Anyway, it's great to see movement on this!

**Comment by stevepiercy** [comment]
Yup, I meant drop testing of EOL versions by "drop support".

One more suggestion: the build is noisy with lots of `WARNI [waitress.queue:115][MainThread] Task queue depth is 1` and we could resolve it by bumping up the number of threads to 6 per this SO post: https://stackoverflow.com/a/55861495/2214933

**Comment by stevepiercy** [comment]
Closed by #400
