### ISSUE TITLE
Travis support Python 3.7 and 3.8

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/deform#376]
We should not use `python: 3.7-dev` per https://docs.travis-ci.com/user/languages/python/#development-releases-support

@ericof what do you think about adopting what we've done in Pyramid?

https://github.com/Pylons/pyramid/blob/master/.travis.yml#L25-L34

```ini
        - python: 3.7
          env: TOXENV=py37
          dist: xenial
          sudo: true
        - python: 3.8-dev
          env: TOXENV=py38
          dist: xenial
          sudo: true
    allow_failures:
        - env: TOXENV=py38
```

I can submit a PR with the change.

**Comment by ericof** [comment]
@stevepiercy Please, do it.  Thanks

**Comment by stevepiercy** [comment]
PR #377 submitted, waiting for build to run.
