### ISSUE TITLE
Error: No select2/compat/containerCss

### ISSUE THREAD

**Issue by davidemoro** [Pylons/deform#380]
Hi,

I'm playing for the first time with a Select2Widget (deform==2.0.5):
 ```
            pepper = colander.SchemaNode(
                colander.String(),
                widget=deform.widget.Select2Widget(values=choices)
                )
```

and I'm experiencing a js error *Error: No select2/compat/containerCss*.

Having a look at this issue I found this entry:
https://github.com/select2/select2/issues/3302

explaining that the *select2.full.js* should be used.

**Comment by stevepiercy** [comment]
I don't get the error, and neither does [this demo example](http://deformdemo.repoze.org/select2/) on Google Chrome. You'll need to provide more information.

**Comment by stevepiercy** [comment]
I'm closing this issue due to no follow up and inactivity. Please reopen with more information if available.
