### ISSUE TITLE
Adding 2 Submit buttons in deform

### ISSUE THREAD

**Issue by vinay-is** [Pylons/deform#383]
I have a use case in which I have a very big HTML form. So I want to add a submit button one at the top and other at the bottom of my Form (bottom is the default option in deform Form). Is this possible? If yes then can you please elaborate how we can do this.

**Comment by stevepiercy** [comment]
@vinay-is please read https://pylonsproject.org/community-support.html

The issue tracker is the last place you should ask for support. It is primarily for reporting bugs or doing development.

That said, deform does not support it out of the box. You would need to customize the form template. See: https://docs.pylonsproject.org/projects/deform/en/latest/templates.html#overriding-the-default-templates and specifically this template: https://github.com/Pylons/deform/blob/master/deform/templates/form.pt
