### ISSUE TITLE
link broken in deform/basics

### ISSUE THREAD

**Issue by srttorres** [Pylons/deform#387]
https://docs.pylonsproject.org/projects/deform/en/latest/basics.html has some links of examples at the end:

- To see an “add form” in action that follows the schema in this chapter, visit http://deformdemo.repoze.org/sequence_of_mappings/.

- To see a “readonly edit form” in action that follows the schema in this chapter, visit http://deformdemo.repoze.org/readonly_sequence_of_mappings/

But, both links  are broken.

Here is what happens on both:

       \          SORRY                   /
         \                                    /
          \    This page does     /
                not exist yet.        

Is it under construction?

**Comment by stevepiercy** [comment]
See https://github.com/Pylons/deformdemo/issues/58
