### ISSUE TITLE
Money Input not working

### ISSUE THREAD

**Issue by nesiax** [Pylons/deform#412]
Hi, I am playing with the MoneyInput under version 2.0.7 and it shows the following error:
 
jquery.maskMoney-1.4.1.js:166 Uncaught TypeError: Cannot read property 'msie' of undefined
    at HTMLInputElement.blurEvent (jquery.maskMoney-1.4.1.js:166)
    at HTMLInputElement.dispatch (jquery-2.0.3.min.js:5)
    at HTMLInputElement.y.handle (jquery-2.0.3.min.js:5)

The error can be removed following this instructions:

https://stackoverflow.com/a/39225835

However, if I have another mask fields then the non-MoneyInput like the Text Input Masks will not work.

So you can test that easily having just one Colander class with one MoneyInput and one TextInput and you will see the problem.

Thanks.

**Comment by stevepiercy** [comment]
@nesiax would you please try out the release of Deform 2.0.14 and verify that the fix in #462 solves the issue for you? If there is still a problem, you may reopen this issue.
