### ISSUE TITLE
Move instructions for setting up a development environment closer to front of contributing.md

### ISSUE THREAD

**Issue by jhaiduce** [Pylons/deform#414]
I'd to propose that we provide instructions for setting up a development environment up front, before telling people how to run tests using tox. That way we can tell people to do "pip install -e '.[dev]'" and the'll get the requirements for linting, unit testing, functional testing, and docs generation with one command.

I'm happy to implement this change (I have a branch almost ready to go for a PR on it already).

**Comment by stevepiercy** [comment]
@jhaiduce is this the PR to which you refer? https://github.com/Pylons/deform/pull/415

**Comment by jhaiduce** [comment]
> @jhaiduce is this the PR to which you refer? #415

No. The PR I referred to isn't created yet. It's just a branch on my local machine right now. Sorry for the confusing language.

**Comment by stevepiercy** [comment]
@jhaiduce OK, I pushed some changes to that PR a few days ago that I think will address this issue. Would you please review #415, and let me know? Thank you!

**Comment by jhaiduce** [comment]
> @jhaiduce OK, I pushed some changes to that PR a few days ago that I think will address this issue. Would you please review #415, and let me know? Thank you!

My apologies, I saw your edits to #415 and haven't had the chance to review them yet. I'll have a look.

**Comment by jhaiduce** [comment]
@stevepiercy I think your edits to #415 address this nicely. Thanks!

**Comment by stevepiercy** [comment]
Closed by #415
