### ISSUE TITLE
Chameleon 3.8.0 changes rendering of `checked` attribute in radios and checkboxes

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/deform#417]
[Chameleon 3.8.0 made changes](https://github.com/malthe/chameleon/blob/master/CHANGES.rst#380-2020-06-25) that affect how radios and checkboxes render `False` values.

- Expose default marker as importable symbol chameleon.tales.DEFAULT_MARKER.
- Removed legacy flag literal_false. To get a similar behavior, use boolean_attributes.

For now, the workaround is to pin Chameleon < 3.8.0.

See https://github.com/malthe/chameleon/issues/318

**Comment by stevepiercy** [comment]
Fixed by #418

**Comment by stevepiercy** [comment]
@sbrunner how about now? 😉

**Comment by sbrunner** [comment]
Thanks :-)
