### ISSUE TITLE
2.0.11+: Dropped Python 2 support?

### ISSUE THREAD

**Issue by icemac** [Pylons/deform#478]
Starting with version 2.0.11 there are Python-3-only wheels on PyPI. (Which cannot be installed by pip on Python 2.)

But the trove classifiers still mention Python 2.7 support and the change log does not mention dropping Python 2 support (but only 3.4).

What was the intention? Should 2.0.x releases still support Python 2.7?

**Comment by icemac** [comment]
```
$ bin/pip2.7 install "deform>=2.0.11"
ERROR: Could not find a version that satisfies the requirement deform>=2.0.11 (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.8.1, 0.9, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9, 0.9.10.dev0, 2.0a1, 2.0a2, 2.0b1, 2.0b2, 2.0b3, 2.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.0.10)
ERROR: No matching distribution found for deform>=2.0.11
```

**Comment by stevepiercy** [comment]
Thanks for the report. The lack of a proper dist is a mistake.

It looks like we are missing a step in our [RELEASING.txt](https://github.com/Pylons/deform/blob/master/RELEASING.txt#L57) or in [tox.ini](https://github.com/Pylons/deform/blob/master/tox.ini#L95) itself.

**Comment by stevepiercy** [comment]
Argh, I'm bad at regex.

```
$VENV/bin/twine upload dist/deform-X.Y.Z-*
```

Should be:

```
$VENV/bin/twine upload dist/deform-X.Y.Z*
```

**Comment by stevepiercy** [comment]
I pushed the latest https://pypi.org/project/deform/2.0.14/#files.

I'll go back and do the missing ones as well.

**Comment by stevepiercy** [comment]
- https://pypi.org/project/deform/2.0.13/#files
- https://pypi.org/project/deform/2.0.12/#files
- https://pypi.org/project/deform/2.0.11/#files

All done. Sorry about that. I've also updated the docs. Would you please verify?

**Comment by stevepiercy** [comment]
@icemac I'm going to close this issue, now that I've added the sdists. Please reopen if that is not the case for you.

**Comment by icemac** [comment]
Thank you for the quick fix.
