### ISSUE TITLE
Travis-CI.org is toast

### ISSUE THREAD

**Issue by tisdall** [Pylons/deform#502]
Just an FYI I discovered today... Travis-CI has decided to pull the plug on the travis-ci.org services and require transitioning over to their ".com" service.  However, there seems to be [some issues around the transition](https://travis-ci.community/t/extremely-poor-official-communication-of-the-org-shutdown/10568).  The "shutdown" was scheduled for Dec 31, 2020, so any future PRs may never actually run tests.

**Comment by stevepiercy** [comment]
Thanks for the report. We already made the switch to GitHub Actions for [Deform](https://github.com/Pylons/deform/pull/495) and DeformDemo a couple months ago. Several other Pylons Project projects have also made the switch, but not all.
